### ISSUE TITLE
Extension won't reconnect to my twitch account after changing username

### ISSUE THREAD

**Issue by DevonRumbold** [Friss/TwitchNotifier#11]
I changed my twitch username a little while ago and sometimes when entering my username to update my followed channels it just doesn't work. Now I can't seem to get it to accept my username at all, though I can still add individual streamers manually. I'm using it on Edge, if that makes a difference.

**Comment by Friss** [comment]
@DevonRumbold twitch shutdown the API I used to fetch follows so I'll be removing that feature for now. For me to get the same information I'd need to spin up an auth flow that I'm not really wanting to implement just to keep this extension simple.

**Comment by Remco0o** [comment]
@Friss when will it be updated?
